name: learning triggers

on:
    workflow_dispatch:

jobs:
    my-first-job:
        runs-on: ubuntu-latest
        steps: 
            - name: first job
              run: echo "Hello from Github Actions!"

            - name: second job
              run: cat /etc/os-release


