name: Runner Exploration

on:
  workflow_dispatch:

jobs:
  validation-job:
    runs-on: ubuntu-latest
    steps:
      - name: What is installed?
        run: |
          echo "checking the installed softwares version"
          python --version
          aws --version
          docker --version
          ansible --version
          unzip --version
          jq --version
          which unzip
          which jq
