name: Secrets Lab

on:
    workflow_dispatch:

jobs:
    reveal-nothing:
        runs-on: ubuntu-latest
        steps:
            - name: Attempt to log secrets
              run: |
                  echo "the username is ${{ vars.MY_USERNAME}}"
                  echo "the secret is ${{secrets.MY_SECRET_PASSWORD}}"

            - name: shell variable test
              run: |
                  echo "the local env var is ${MY_MAPPED_SECRET}"
              env:
                  MY_MAPPED_SECRET: ${{secrets.MY_SECRET_PASSWORD}}
